/* data.js — everything the trainer knows, each piece tagged with where it came from.
   Rubric text is VERBATIM from the two marking sheets. Model lines come from the course's own demo videos
   (transcribed locally 8 Oct 2026) wherever a demo exists; anything else says where it is from. */
(function () {
  'use strict';

  /* ---------- sources ---------- */
  const SRC = {
    'rub-vs': { label: 'VS rubric', full: 'Practical Skills Assessment: Vital Signs, BN2 722.556 assessment tool (Canvas: Vital Signs Assessment Tool.pdf)' },
    'rub-ma': { label: 'Med admin rubric', full: '722.544 Medication Administration Competence sheet (Canvas: Assessment 3 sheet, Student)' },
    'brief-ma': { label: 'Med admin brief', full: 'Canvas assignment page: Medication Administration Practical Assessment (CLS), Version 2' },
    'brief-vs': { label: 'VS brief', full: 'Canvas assignment page: Vital Signs Practical Assessment' },
    'vid-vs': { label: 'VS demo video', full: 'Canvas video “BN2 vital signs assessment” (Janine as student, Joan as preceptor, patient Mr John Luke)' },
    'vid-ma': { label: 'Joan’s role-play video', full: 'Canvas video “Documentation & Medication Administration Role Play” (Joan as RN, Diane as student, Mr Luke). Joan: “the drug used is different but everything else is almost exactly the same”' },
    'deck-vs': { label: 'Janine’s VS deck', full: 'Vital Signs 2026.pptx (Janine Craig, 722.556)' },
    'deck-ma1': { label: 'Joan’s deck 05 pt 1', full: '05. Medication Administration and Patient Education (1) 2026 (Joan, 722.544)' },
    'deck-ma2': { label: 'Joan’s deck 05 pt 2', full: '05. Medication Administration and Patient Education (2) 2026 (Joan, 722.544)' },
    'nmc': { label: 'NMC user guide', full: 'HQSC National Medication Chart user guide, 3rd ed. 2021 (on Canvas)' },
    'chart': { label: 'Mr Luke’s chart', full: 'Canvas: Mr Lukes chart 2022.pdf (8 Day National Medication Chart, John Luke, DGY 2963)' },
    'pp': { label: 'Potter & Perry (textbook)', full: 'Potter & Perry two-step BP method, as taught in nursing schools (not written out in Janine’s slides)' },
    'healthify': { label: 'Healthify', full: 'healthify.nz medicine pages (metoprolol, paracetamol), the plain-language NZ source' },
    'ds-para': { label: 'Paracetamol data sheet', full: 'Medsafe NZ data sheet, Pacimol 500 mg (the one Joan’s pharmacokinetics deck cites)' },
    'ds-meto': { label: 'Metoprolol CR data sheet', full: 'Medsafe NZ data sheet, metoprolol succinate CR (Myloc CR)' },
    'quiz-vs': { label: 'Janine’s VS quiz', full: 'Canvas: Vital Signs Quiz (722.556), Janine’s own questions' },
    'deck-ai2det': { label: 'BN1 AI2DET slides', full: '722.553 Hand hygiene and bed making 2026 (slides 27–33): the AI2DET communication memory aid' },
    'tool': { label: 'Trainer tip', full: 'The trainer’s own advice. Not from your course material; check it against what your lecturer says.' },
  };

  /* ---------- rubrics, verbatim ---------- */
  const RUBRIC = {
    vs: {
      title: 'Practical Skills Assessment: Vital Signs',
      rule: 'Met / Not Met. Two attempts. You must pass to pass the course.',
      sections: [
        { h: 'Assessment and planning', lines: [
          ['vs.a1', 'Check patient’s chart to identify the need for these observations to be taken, and recorded'],
          ['vs.a2', 'collects all appropriate equipment ensuring it is in working order'],
          ['vs.a3', 'organises safe environment'] ] },
        { h: 'Implementation', lines: [
          ['vs.i1', 'Hand decontamination using hand sanitiser or washing with soap and water'],
          ['vs.i2', 'Introduces self and confirm how the patient prefers to be addressed.'],
          ['vs.i3', 'Identifies correct patient by: Checking patient’s name & birth date verbally against chart, and visually on patient’s wristband, including NHI, against chart'],
          ['vs.i4', 'Explains the procedure to the patient that it involves touching their ear and their arm'],
          ['vs.i5', 'Gain consent from the patient'],
          ['vs.i6', 'Assess and document vital signs on appropriate chart: temperature (using tympanic thermometer)'],
          ['vs.i7', 'pulse rate (count for 30 seconds)'],
          ['vs.i8', 'respiratory rate (count for 30 seconds)'],
          ['vs.i9', 'blood pressure (using two-step technique)'],
          ['vs.i10', 'Adheres to infection control practices'],
          ['vs.i11', 'Communicates effectively with patient'],
          ['vs.i12', 'Ensures safe environment on leaving patient'],
          ['vs.i13', 'Cleans and returns equipment'],
          ['vs.i14', 'Hand decontamination'] ] },
        { h: 'Evaluation', lines: [
          ['vs.e1', 'Accurately documents findings directly on vital signs chart'],
          ['vs.e2', 'Identifies and reports normal/abnormal findings to Registered Nurse (including discussion of normal adult ranges for all vital signs)'],
          ['vs.e3', 'Systematic manner of completion'],
          ['vs.e4', 'Demonstrates culturally safe practices'],
          ['vs.e5', 'Demonstrates therapeutic communication throughout'] ] },
      ],
    },
    ma: {
      title: '722.544 Medication Administration Competence',
      rule: 'Met / Not Met. One attempt plus one resit. You must show every step.',
      sections: [
        { h: 'Apply knowledge of the medication (to the RN and the patient)', lines: [
          ['ma.k1', 'Generic Medication Name'],
          ['ma.k2', 'Indication(s) for use. Must be relevant to scenario'],
          ['ma.k3', 'Common adverse effects'] ] },
        { h: 'Administers under RN supervision, with these steps/checks', lines: [
          ['ma.a1', 'Right patient (verbal check & visual wristband ID check)'],
          ['ma.a2', 'Right medication (generic name)'],
          ['ma.a3', 'Right dose'],
          ['ma.a4', 'Right time (as prescribed, frequency & check when last dose given)'],
          ['ma.a5', 'Right route'],
          ['ma.a6', 'Right to refuse (informed consent)'],
          ['ma.a7', 'Right indication (with relevance to scenario)'],
          ['ma.a8', 'Check & interpret medication expiry date'],
          ['ma.a9', 'Check for patient allergies (chart & verbal check)'],
          ['ma.a10', 'Maintain infection control practices'],
          ['ma.a11', 'Overall the process is methodical, organised, and safe for the patient and the student nurse'] ] },
        { h: 'Accurately documents under RN supervision', lines: [
          ['ma.d1', 'Correct medication'],
          ['ma.d2', 'Correct date, time, dose'],
          ['ma.d3', 'Appropriate initials'] ] },
        { h: 'Patient education: Ask, Build, Check', lines: [
          ['ma.e1', 'Ask: Patient’s knowledge assessed'],
          ['ma.e2', 'Build: Relevant information explained, appropriate terms'],
          ['ma.e3', 'Check: Evaluation of patient’s understanding assessed'],
          ['ma.e4', 'Describe to the RN the 3 ABC steps of medication education'],
          ['ma.e5', 'Communication with the patient throughout the assessment is respectful, clear, and patient‑centred'] ] },
      ],
    },
  };

  /* ---------- the patient (from the course's own chart + VS demo) ---------- */
  const PATIENT = {
    name: 'John Luke', first: 'John', title: 'Mr Luke',
    dob: '16/12/1942', dobSay: 'the sixteenth of December, 1942',
    nhi: 'DGY 2963', nhiSay: 'D G Y 2963',
    note: 'Name, NHI and date of birth are from Mr Luke’s chart on Canvas and the VS demo video. On the day, read the chart in front of you. It may differ.',
  };

  /* ---------- normal adult ranges, as the course teaches them ---------- */
  const NORMALS = [
    { k: 'temp', name: 'Temperature', range: '36.5–37.5 °C', say: 'thirty-six point five to thirty-seven point five degrees', src: ['deck-vs', 'slide 30'], extra: '36.0–36.4 usually safe · 37.6–37.9 low-grade fever · over 38 pyrexia · under 35 hypothermia' },
    { k: 'hr', name: 'Heart rate', range: '60–100 bpm', say: 'sixty to a hundred beats per minute', src: ['vid-vs', '11:42'], extra: 'under 60 bradycardia · over 100 tachycardia (deck slide 24)' },
    { k: 'rr', name: 'Respiratory rate', range: '12–20 breaths/min', say: 'twelve to twenty breaths per minute', src: ['deck-vs', 'slide 10'], extra: 'under 12 bradypnoea · over 20 tachypnoea' },
    { k: 'bp', name: 'Blood pressure', range: '110–140 / 60–90 mmHg', say: 'systolic one-ten to one-forty, diastolic sixty to ninety', src: ['deck-vs', 'slide 17'], extra: 'systolic = first sound · diastolic = last sound' },
    { k: 'spo2', name: 'Oxygen saturation', range: '95–100 %', say: 'ninety-five to a hundred percent', src: ['deck-vs', 'slide 13'], extra: 'not on the VS rubric, but on Janine’s quiz' },
  ];

  /* ---------- the two drugs in the med admin scenario ---------- */
  const DRUGS = {
    para: {
      key: 'para', generic: 'paracetamol', brands: 'Panadol, Pamol, Pacimol',
      order: 'Paracetamol 1 g PO qid', dose: '1 g', strength: '500 mg tablets', tabs: 'two 500 mg tablets', tabsN: 2,
      klass: 'analgesic (pain reliever; also lowers fever)',
      indication: 'his recurrent backache',
      indicationPlain: 'for the backache you’ve been getting',
      freq: 'qid, four times a day. Recommended times on the chart: 0600, 1200, 1800, 2200',
      lastDose: 'At least 4 hours since the last dose, and no more than 4 g in 24 hours. 1 g qid is already 4 g a day, so ANY other paracetamol (Panadol from home, cold-and-flu products) would be too much.',
      adverse: 'At the right dose, side effects are very rare: allergic reactions (rash, swelling, anaphylaxis), bronchospasm in people sensitive to aspirin/NSAIDs, and liver problems. The big risk is liver damage from too much.',
      adversePlain: 'Most people get no side effects from paracetamol. If you get a rash, swelling, or trouble breathing, ring your bell straight away. The main thing is never to take more than you’re given, because too much can harm your liver.',
      considerations: ['Pain score before, and check it worked about 30–60 minutes after', 'Time since the last dose (at least 4 hours) and the 24-hour total (max 4 g)', 'Ask about other paracetamol he might be taking (Panadol from home, cold-and-flu products)', 'Liver disease or heavy alcohol use means caution (Special Care box: hepatic impairment)'],
      takeIt: 'Swallow with a glass of water.',
      checkBack: 'what this tablet is for, and what you’d do if you got a rash or felt unwell',
      src: [['ds-para', '4.2–4.8'], ['healthify', 'paracetamol'], ['deck-ma1', 'deck 01: generic vs brand']],
    },
    meto: {
      key: 'meto', generic: 'metoprolol succinate', brands: 'Betaloc CR, Myloc CR',
      order: 'Metoprolol Succinate CR 47.5 mg PO daily', dose: '47.5 mg', strength: '47.5 mg controlled-release (CR) tablet', tabs: 'one 47.5 mg CR tablet', tabsN: 1,
      klass: 'beta-adrenoceptor blocker (beta blocker): blocks beta receptors, so the heart beats slower and less forcefully and blood pressure drops',
      indication: 'his high blood pressure (higher than usual lately) and his heart failure',
      indicationPlain: 'to bring your blood pressure down and take some of the strain off your heart',
      freq: 'daily, once a day, usually in the morning (Mane 0800 on the chart)',
      lastDose: 'Once a day only. Check the administration record that today’s dose hasn’t already been given.',
      adverse: 'Very common: tiredness. Common: slow heart rate (bradycardia), dizziness especially when standing up, cold hands and feet, headache, nausea, breathlessness on exertion. Never stop it suddenly.',
      adversePlain: 'It can make you feel tired, a bit dizzy when you stand up, or give you cold hands and feet. Because of the dizziness, please ring your bell before you get up for the next little while, so we can help you and you don’t fall.',
      considerations: ['Check his pulse and BP BEFORE giving it. If either is low, withhold and tell the RN.', 'Falls risk (dizziness, postural drop): he’s 79', 'Swallow whole. It can be halved, but NEVER crushed or chewed (controlled release)', 'Don’t stop suddenly: it can make heart failure worse', 'Asthma or wheeze: beta blockers can cause bronchospasm (Joan’s pharmacodynamics deck: metoprolol blocks salbutamol)'],
      takeIt: 'Swallow it whole with a glass of water. Don’t crush or chew it.',
      checkBack: 'what this tablet is for, and what you’d do if you felt dizzy',
      src: [['ds-meto', '4.4, 4.8'], ['healthify', 'metoprolol'], ['deck-ma1', 'deck 01/04: beta blocker, antagonist']],
    },
  };

  /* ---------- steps ----------
     kind: 'do' (you do it) · 'say' (you say it; listened for) · 'pt' (patient speaks) · 'rn' (RN speaks)
     to:   who you are talking to when kind = 'say' ('pt' | 'rn')
     line: the model line (spoken by the app for pt/rn; shown as your model for say)
     keys: groups the mic listens for (all groups needed, any word in a group)
     lines: rubric line ids this step earns · src: [sourceKey, where]
     trap: the mistake people make here · bp: part of the two-step BP chain */
  const VS = [
    // ---- before you go in (with your preceptor, at the chart) ----
    { id: 'vs-chart', ph: 'At the chart, with your preceptor', kind: 'say', to: 'rn', t: 'Check the chart: right patient, obs due',
      cue: 'Point to the name, date of birth and NHI on the vital signs chart. Say you’ll check them verbally and on the wristband. Look at when obs were last done.',
      line: 'This is the adult vital signs chart for John Luke. His date of birth is here and his NHI is here. I’ll check those verbally with him and on his wristband. No one has taken his vital signs yet today, so I’ll be doing them now.',
      keys: [['chart'], ['date of birth', 'nhi', 'wristband', 'bracelet']], lines: ['vs.a1'], src: ['vid-vs', '00:00'] },
    { id: 'vs-plan', ph: 'At the chart, with your preceptor', kind: 'say', to: 'rn', t: 'Say your plan and your order',
      cue: 'Temperature, then pulse, then respirations (without telling him), then blood pressure last. Document as you go, then report back.',
      line: 'I’ll take his temperature first, then his pulse, then his respiratory rate, but I won’t tell him I’m doing that, because breathing changes if people know. Then his blood pressure last. I’ll document as I go and report the findings to you.',
      keys: [['temperature', 'temp'], ['pulse', 'heart rate'], ['respiratory', 'breathing', 'respirations'], ['blood pressure', 'bp']], lines: ['vs.e3'], src: ['vid-vs', '00:00'] },
    { id: 'vs-equip', ph: 'At the chart, with your preceptor', kind: 'do', t: 'Get the equipment and check it works',
      cue: 'Tympanic thermometer + probe covers · manual cuff in the RIGHT SIZE (have a bigger one ready) · stethoscope · watch with a second hand · the vital signs chart · blue or black pen · wipes. Check each one actually works.',
      line: 'I’ll just make sure everything’s in working order. I’m going to use the larger cuff on Mr Luke, but I’ve got a medium one here as well.',
      lines: ['vs.a2'], src: ['vid-vs', '01:00'] },
    { id: 'vs-hh1', ph: 'At the chart, with your preceptor', kind: 'do', t: 'Hand hygiene',
      cue: 'Sanitise your hands before you go to the patient (or wash with soap and water).',
      lines: ['vs.i1', 'vs.i10'], src: ['rub-vs', 'Implementation'] },

    // ---- at the bedside ----
    { id: 'vs-greet', ph: 'At the bedside', kind: 'say', to: 'pt', t: 'Greet him warmly',
      cue: 'Kind, unhurried. A small check-in before the task.',
      line: 'Good morning. How are you today?', keys: [['morning', 'afternoon', 'hello', 'kia ora', 'hi']],
      lines: ['vs.i11', 'vs.e5'], src: ['vid-vs', '02:01'] },
    { id: 'vs-greet-pt', ph: 'At the bedside', kind: 'pt', t: 'Mr Luke answers', line: 'Oh, I’m doing okay. A little bit tired this morning.', src: ['vid-vs', '02:01'] },
    { id: 'vs-intro', ph: 'At the bedside', kind: 'say', to: 'pt', t: 'Introduce yourself AND your preceptor',
      cue: 'Your name, that you’re a nursing student from MIT, and who your preceptor is.',
      line: 'My name’s ___. I’m a second-year nursing student from MIT, and this is my preceptor ___, who I’m working with today.',
      keys: [['my name', 'name is', 'im '], ['student', 'nursing'], ['preceptor', 'working with']], lines: ['vs.i2', 'vs.i11'], src: ['vid-vs', '02:01'] },
    { id: 'vs-id', ph: 'At the bedside', kind: 'say', to: 'pt', t: 'ID check: full name AND date of birth',
      cue: 'Ask him to TELL you. Don’t say his name for him.',
      line: 'Before we go any further, can I just make sure I’ve got the right chart and the right patient? Can you tell me your full name and date of birth, please?',
      keys: [['name'], ['date of birth', 'birthday', 'born', 'birth date']], lines: ['vs.i3'], src: ['vid-vs', '02:01'],
      trap: 'Saying “You’re John Luke, aren’t you?” is a closed question. He has to tell you.' },
    { id: 'vs-id-pt', ph: 'At the bedside', kind: 'pt', t: 'Mr Luke answers', line: 'John Luke. Sixteenth of December, 1942.', src: ['vid-vs', '02:35'] },
    { id: 'vs-band', ph: 'At the bedside', kind: 'say', to: 'pt', t: 'Wristband: name, DOB AND NHI against the chart',
      cue: 'Ask to look at the band. Read the name, date of birth AND NHI on the band against the chart, out loud.',
      line: 'Is it okay if I check your wristband as well? John Luke, 16th of December 1942, and NHI D G Y 2963. That matches the chart.',
      keys: [['wristband', 'band', 'bracelet', 'wrist'], ['nhi', 'number']], lines: ['vs.i3'], src: ['vid-vs', '02:35'],
      trap: 'The NHI is the one people forget. The rubric names it.' },
    { id: 'vs-name', ph: 'At the bedside', kind: 'say', to: 'pt', t: 'Ask what he’d like to be called',
      cue: 'Preferred name. This is culturally safe practice and it’s a rubric line on its own.',
      line: 'What would you like me to call you today?', keys: [['call you', 'like to be called', 'prefer', 'what would you like']],
      lines: ['vs.i2', 'vs.e4'], src: ['vid-vs', '02:35'] },
    { id: 'vs-name-pt', ph: 'At the bedside', kind: 'pt', t: 'Mr Luke answers', line: 'Oh, John’s fine.', src: ['vid-vs', '03:07'] },
    { id: 'vs-explain', ph: 'At the bedside', kind: 'say', to: 'pt', t: 'Explain: ear, wrist, arm, cuff pumped up twice',
      cue: 'Name the touching: the top of his ear, his wrist, his arm. The cuff goes up twice. About 10–12 minutes. Any questions?',
      line: 'We’re going to do your vital signs. I’ll take your temperature with a thermometer that goes in your ear, so I’ll need to touch the top of your ear. I’ll take your pulse, so I’ll touch your wrist. Then your blood pressure: a cuff goes on your arm and gets pumped up. We do that twice. It’ll take about ten to twelve minutes. Any questions about that?',
      keys: [['ear'], ['arm'], ['cuff', 'blood pressure', 'pump']], lines: ['vs.i4', 'vs.i11'], src: ['vid-vs', '03:17'],
      trap: 'The rubric line is literally “involves touching their ear and their arm”. Say both words.' },
    { id: 'vs-consent', ph: 'At the bedside', kind: 'say', to: 'pt', t: 'Ask for consent',
      cue: 'A clear question he can say no to.',
      line: 'Are you happy for me to go ahead and do that now?', keys: [['happy', 'okay', 'alright', 'is that ok', 'go ahead', 'consent']],
      lines: ['vs.i5', 'vs.e4'], src: ['vid-vs', '03:49'] },
    { id: 'vs-consent-pt', ph: 'At the bedside', kind: 'pt', t: 'Mr Luke answers', line: 'Yes, please.', src: ['vid-vs', '03:49'] },
    { id: 'vs-env', ph: 'At the bedside', kind: 'do', t: 'Make the space safe',
      cue: 'Privacy (curtain) · brakes on · clear the area · him sitting comfortably with feet flat · your equipment within reach.',
      lines: ['vs.a3'], src: ['rub-vs', 'Assessment and planning'] },

    // ---- temperature ----
    { id: 'vs-temp', ph: 'Temperature', kind: 'do', t: 'Tympanic (ear) temperature',
      cue: 'New probe cover → gently pull the top of the ear up and back → probe in snugly → press → read → eject the cover into the bin.',
      lines: ['vs.i6', 'vs.i10'], src: ['rub-vs', 'temperature (using tympanic thermometer)'] },
    { id: 'vs-temp-doc', ph: 'Temperature', kind: 'do', t: 'Chart it now',
      cue: 'Straight onto the vital signs chart: mark with an X, or write the value if it’s off the scale. Date and 24-hour time at the top of the column.',
      lines: ['vs.e1'], src: ['deck-vs', 'slide 33: always document at the time'],
      trap: 'Never on a paper towel or your hand. Janine’s slide says so in those words.' },

    // ---- pulse + respirations ----
    { id: 'vs-pulse', ph: 'Pulse and respirations', kind: 'do', t: 'Radial pulse: 30 seconds × 2',
      cue: 'Two or three fingers (not your thumb) on the radial pulse. Count for 30 seconds and double it. If it’s IRREGULAR, count a full minute. Feel the rhythm and strength too.',
      lines: ['vs.i7'], src: ['deck-vs', 'slides 23, 25'] },
    { id: 'vs-resp', ph: 'Pulse and respirations', kind: 'do', t: 'Respirations: keep your fingers on the wrist',
      cue: 'Don’t announce it. Leave your fingers on his wrist and count breaths for 30 seconds × 2 (a full minute if irregular). Note depth and effort.',
      lines: ['vs.i8'], src: ['deck-vs', 'slide 9'],
      trap: 'If he knows you’re counting, his breathing changes.' },
    { id: 'vs-pr-doc', ph: 'Pulse and respirations', kind: 'do', t: 'Chart HR (X) and RR (the number in its box)',
      cue: 'Heart rate: mark with an X. Respiratory rate: write the actual number in the box.',
      lines: ['vs.e1'], src: ['vid-vs', '16:16'] },

    // ---- blood pressure, two-step ----
    { id: 'bp-pos', ph: 'Blood pressure: two-step', kind: 'do', bp: true, t: 'Position the arm',
      cue: 'Sleeve up (bare arm) · arm supported at heart level, palm up · him sitting, feet flat, not talking.',
      lines: ['vs.i9'], src: ['pp', 'positioning'] },
    { id: 'bp-size', ph: 'Blood pressure: two-step', kind: 'say', to: 'pt', bp: true, t: 'Check the cuff size',
      cue: 'Check the range lines on the cuff fit his arm. Too small reads falsely HIGH.',
      line: 'I’m just going to measure to make sure you’ve got the right size cuff.', keys: [['size', 'cuff', 'measure']],
      lines: ['vs.i9'], src: ['vid-vs', '07:00'] },
    { id: 'bp-feel', ph: 'Blood pressure: two-step', kind: 'do', bp: true, t: 'Find the brachial artery',
      cue: 'Feel the brachial pulse on the inside of the elbow crease (little-finger side of the biceps tendon). Ask him to keep his arm nice and straight.',
      line: 'I’m just finding the brachial artery here. Keep your arm nice and straight for me.',
      lines: ['vs.i9'], src: ['vid-vs', '07:46'] },
    { id: 'bp-wrap', ph: 'Blood pressure: two-step', kind: 'do', bp: true, t: 'Wrap the cuff',
      cue: 'Cuff fully deflated. Artery marker over the brachial artery. Bottom edge about 2–3 cm above the elbow crease. Snug: two fingers fit under it.',
      lines: ['vs.i9'], src: ['pp', 'cuff placement'] },
    { id: 'bp-s1', ph: 'Blood pressure: two-step', kind: 'do', bp: true, t: 'STEP 1: feel the pulse, pump until it disappears, +30',
      cue: 'Fingers on the radial (or brachial) pulse. Close the valve. Pump until the pulse disappears, then 30 mmHg more. NO stethoscope yet.',
      line: 'I’m just going to pump it up the first time, to get an estimate of what your blood pressure is.',
      lines: ['vs.i9'], src: ['vid-vs', '08:20'] },
    { id: 'bp-s1b', ph: 'Blood pressure: two-step', kind: 'do', bp: true, t: 'Let it down and note where the pulse comes back',
      cue: 'Open the valve slowly. The number where you FEEL the pulse come back is the estimated systolic. (In the video: about 110.)',
      line: 'So I got about 110. That’s what we call an approximate systolic.',
      lines: ['vs.i9'], src: ['vid-vs', '09:04'] },
    { id: 'bp-wait', ph: 'Blood pressure: two-step', kind: 'do', bp: true, t: 'Deflate fully, then wait 30 seconds',
      cue: 'Let ALL the air out. Wait 30 seconds before step 2, so the blood in his arm settles.',
      lines: ['vs.i9'], src: ['pp', 'deflate fully, wait 30 s'],
      trap: 'Pumping straight back up is the retry spiral: the arm congests, the sounds get fainter, and every try gets harder.' },
    { id: 'bp-steth', ph: 'Blood pressure: two-step', kind: 'do', bp: true, t: 'STEP 2: stethoscope ON the brachial, BEFORE you pump',
      cue: 'Earpieces pointing forward (towards your nose). Tap the chest piece to check it’s open. Rest it LIGHTLY on the brachial artery, below the cuff, not tucked under it.',
      lines: ['vs.i9'], src: ['pp', 'auscultation'],
      trap: 'This is the one you were pulled up on. The stethoscope goes on FIRST. Pumping comes after.' },
    { id: 'bp-s2', ph: 'Blood pressure: two-step', kind: 'say', to: 'pt', bp: true, t: 'Pump to estimate + 30',
      cue: 'Close the valve. Pump to 30 mmHg above your step-1 estimate (110 → 140).',
      line: 'Now I’m going to pump it up to 30 above that, so up to 140.', keys: [['thirty', '30', 'above', 'hundred and forty', '140', 'pump']],
      lines: ['vs.i9'], src: ['vid-vs', '09:04'] },
    { id: 'bp-s2b', ph: 'Blood pressure: two-step', kind: 'do', bp: true, t: 'Release 2–3 mmHg a second and listen',
      cue: 'Turn the valve slowly so the needle falls 2–3 mmHg per second. FIRST clear tap = systolic. Keep going. Where the sound DISAPPEARS = diastolic. Then let it all down and take the cuff off.',
      lines: ['vs.i9'], src: ['pp', 'deflation rate 2–3 mmHg/s'] },
    { id: 'bp-tell', ph: 'Blood pressure: two-step', kind: 'say', to: 'pt', bp: true, t: 'Tell him the result in plain words',
      cue: 'Give the number and what it means. Ask if he knows his usual BP.',
      line: 'That was 110 over 60. That’s normal, on the low side of normal. Do you know what your blood pressure usually is?',
      keys: [['over'], ['normal', 'high', 'low', 'usual']], lines: ['vs.i11', 'vs.e5'], src: ['vid-vs', '09:16'] },
    { id: 'bp-doc', ph: 'Blood pressure: two-step', kind: 'do', bp: true, t: 'Chart the BP',
      cue: 'An arrow pointing onto the systolic line, an arrow pointing onto the diastolic line, joined with a dotted line. (Only the systolic scores on the EWS, but you chart both.)',
      lines: ['vs.e1'], src: ['vid-vs', '17:03'] },

    // ---- report & leave safe ----
    { id: 'vs-report-ask', ph: 'Report and leave him safe', kind: 'say', to: 'pt', t: 'Tell him you’ll talk to your preceptor',
      cue: 'Include him. Don’t talk over him.',
      line: 'John, I’m just going to talk to my preceptor about your results here. Is that okay?', keys: [['preceptor', 'nurse'], ['okay', 'alright', 'is that']],
      lines: ['vs.e4', 'vs.e5'], src: ['vid-vs', '11:07'] },
    { id: 'vs-report-rn', ph: 'Report and leave him safe', kind: 'rn', t: 'Your preceptor asks', line: 'Okay, just talk me through what you’ve done so far.', src: ['vid-vs', '11:17'] },
    { id: 'vs-report', ph: 'Report and leave him safe', kind: 'say', to: 'rn', t: 'Report every value WITH its normal range',
      cue: 'Date and time on the chart, then each value, normal or abnormal, and the normal adult range for EACH one. Mention how you counted (30 seconds × 2).',
      line: 'I put the date and the time in 24-hour time. His temperature was 36.9, within the normal range of 36.5 to 37.5. His pulse was 64; normal is 60 to 100. I counted for 30 seconds and doubled it. His respiratory rate was 12; normal is 12 to 20. His blood pressure was 110 over 60; normal systolic is 110 to 140 and diastolic 60 to 90, so he’s on the low side of normal.',
      keys: [['temperature', 'temp'], ['pulse', 'heart rate'], ['respiratory', 'breathing', 'resp'], ['blood pressure', 'over'], ['normal', 'range']],
      lines: ['vs.e2', 'vs.e3'], src: ['vid-vs', '11:21'],
      trap: 'The rubric wants the normal adult range for ALL the vital signs, not just the abnormal one.' },
    { id: 'vs-rn-q', ph: 'Report and leave him safe', kind: 'rn', t: 'Your preceptor asks', line: 'What’s your responsibility as a student if any of those were outside the normal range, too high or too low?', src: ['vid-vs', '12:33'] },
    { id: 'vs-rn-a', ph: 'Report and leave him safe', kind: 'say', to: 'rn', t: 'Answer: recheck it and report it straight away',
      cue: 'Recheck it, then report it to your preceptor/RN straight away. Never sit on an abnormal value.',
      line: 'I’d recheck it, and I’d always report it to you straight away if anything was outside the normal range.',
      keys: [['report', 'tell', 'let you know'], ['recheck', 'check again', 'repeat', 'double check']], lines: ['vs.e2'], src: ['vid-vs', '12:44'] },
    { id: 'vs-close', ph: 'Report and leave him safe', kind: 'say', to: 'pt', t: 'Close the loop with him',
      cue: 'Tell him you’re finished and when you’ll be back.',
      line: 'John, that concludes your vital signs for today. I’ll come back and check on you in about half an hour.',
      keys: [['back', 'check on you', 'half an hour', 'come back']], lines: ['vs.i11', 'vs.e5'], src: ['vid-vs', '13:36'] },
    { id: 'vs-safe', ph: 'Report and leave him safe', kind: 'say', to: 'pt', t: 'Leave him safe: call bell, water, comfortable',
      cue: 'Call bell in his hand or within reach · water within reach · ask: sitting up or back to bed? · take away anything extra (pillow) · brakes on.',
      line: 'If you need anything, here’s your call bell. Just give that a ring. Are you fine sitting up for now, or would you like to go back to bed? Your water’s here.',
      keys: [['bell', 'buzzer', 'call'], ['water', 'drink', 'sitting', 'comfortable', 'bed']], lines: ['vs.i12'], src: ['vid-vs', '13:36'] },
    { id: 'vs-thanks', ph: 'Report and leave him safe', kind: 'say', to: 'pt', t: 'Thank him',
      line: 'Well, thank you very much, and we’ll see you in half an hour.', keys: [['thank']], lines: ['vs.e5'], src: ['vid-vs', '14:25'] },
    { id: 'vs-clean', ph: 'Report and leave him safe', kind: 'do', t: 'Clean the equipment and put it back',
      cue: 'Wipe the cuff, the stethoscope (chest piece and earpieces) and the thermometer, then return them.',
      lines: ['vs.i13', 'vs.i10'], src: ['vid-vs', '14:32'] },
    { id: 'vs-hh2', ph: 'Report and leave him safe', kind: 'do', t: 'Hand hygiene',
      cue: 'Sanitise or wash your hands. Last step, every time.', lines: ['vs.i14', 'vs.i10'], src: ['rub-vs', 'Implementation'] },
    { id: 'vs-doccheck', ph: 'Report and leave him safe', kind: 'do', t: 'Check the chart is complete',
      cue: 'Date and 24-hour time · every value plotted · blue/black pen · any error crossed out with ONE line so it can still be read.',
      lines: ['vs.e1'], src: ['deck-vs', 'slide 33'] },
  ];

  const MA = [
    // ---- drug room / with your RN ----
    { id: 'ma-hh1', ph: 'With your RN, before the bedside', kind: 'do', t: 'Hand hygiene',
      cue: 'Clean hands before you touch the chart or the medicines. The drug room is used by every nurse.',
      line: 'Can I wash my hands first?', lines: ['ma.a10'], src: ['vid-ma', '10:10'] },
    { id: 'ma-chart-id', ph: 'With your RN, before the bedside', kind: 'say', to: 'rn', t: 'Read the chart out loud, finger on it',
      cue: 'Patient sticker: name, NHI, date of birth. The prescriber has also written his name by hand. Use your index finger so your RN can follow.',
      line: 'This is the chart for John Luke, NHI D G Y 2963, date of birth 16th of December 1942. The sticker’s here and the prescriber has written his name and NHI by hand.',
      keys: [['chart'], ['nhi', 'date of birth', 'birth']], lines: ['ma.a11'], src: ['vid-ma', '12:56'],
      trap: 'No name on the chart means no drug. Joan: “no giving drugs to naked charts”.' },
    { id: 'ma-allergy-chart', ph: 'With your RN, before the bedside', kind: 'say', to: 'rn', t: 'Allergies & Adverse Reactions box (the yellow one)',
      cue: 'Read it out: ticked “No”, signed and dated by the prescriber. That only means he was ASKED. You still ask him yourself at the bedside.',
      line: 'Allergies and adverse reactions: ticked no, signed and dated by the prescriber. I’ll still check with him at the bedside.',
      keys: [['allerg'], ['signed', 'dated', 'no allergies', 'ticked']], lines: ['ma.a9'], src: ['vid-ma', '02:15'] },
    { id: 'ma-special', ph: 'With your RN, before the bedside', kind: 'say', to: 'rn', t: 'Special care + supplementary charts',
      cue: 'Special Care Required (renal or hepatic impairment, pregnancy, breastfeeding, anticoagulation) and supplementary charts (insulin, heparin, warfarin). Say what’s ticked.',
      line: 'No special care boxes ticked and no supplementary charts.',
      keys: [['special', 'supplementary', 'renal', 'hepatic', 'impairment']], lines: ['ma.a11'], src: ['vid-ma', '11:53'] },
    { id: 'ma-find', ph: 'With your RN, before the bedside', kind: 'say', to: 'rn', t: 'Find the order: drug, dose, route, frequency, signed',
      cue: 'Regular page: the date, the GENERIC name, dose AND units, route, frequency, prescriber’s signature (it matches the sample signatures on the front page).',
      line: 'On the regular page it’s dated and signed: {order}.',
      keys: [['{generic1}'], ['po', 'orally', 'oral', 'by mouth'], ['signed', 'dated', 'daily', 'qid', 'four times']], lines: ['ma.a2', 'ma.a5', 'ma.d1'], src: ['vid-ma', '13:56'] },
    { id: 'ma-time', ph: 'With your RN, before the bedside', kind: 'say', to: 'rn', t: 'Right time: when was the last dose?',
      cue: 'Look across the administration record: is it due NOW, and when was the last dose given? {lastDose}',
      line: 'It’s prescribed {freqShort}. Looking at the administration record, the last dose was ___, so it’s due now.',
      keys: [['last dose', 'last given', 'last time', 'hasnt had', 'not had', 'due'], ['daily', 'qid', 'four times', 'once a day', 'times a day', 'hours']], lines: ['ma.a4'], src: ['vid-ma', '13:56'] },
    { id: 'ma-know-rn', ph: 'With your RN, before the bedside', kind: 'rn', t: 'Your RN asks', line: 'So can you tell me a little bit about this drug?', src: ['vid-ma', '14:48'] },
    { id: 'ma-know', ph: 'With your RN, before the bedside', kind: 'say', to: 'rn', t: 'Knowledge: generic name, why HE’s on it, side effects',
      cue: 'Technical words are fine with the RN. Generic name · drug class · indication FOR MR LUKE · common adverse effects · one nursing consideration.',
      line: '{generic} is a {klassShort}. He’s on it for {indication}. Common adverse effects are {adverseShort}. {considerShort}',
      keys: [['{generic1}'], ['{indKey}'], ['side effect', 'adverse', '{aeKey}']], lines: ['ma.k1', 'ma.k2', 'ma.k3', 'ma.a7'], src: ['rub-ma', 'Apply knowledge'],
      trap: 'The indication has to be about HIM (“his backache” or “his blood pressure”), not a textbook list.' },
    { id: 'ma-select', ph: 'With your RN, before the bedside', kind: 'say', to: 'rn', t: 'Select the pack: label vs chart (check 1)',
      cue: 'Read the label: generic name and strength against the chart. Work out how many: {tabs}.',
      line: 'The label says {strength}. It’s prescribed {dose}, so that’s {tabs}.',
      keys: [['{generic1}', 'label'], ['tablet', 'tablets', 'mg', 'milligram', 'gram']], lines: ['ma.a2', 'ma.a3'], src: ['vid-ma', '17:07'] },
    { id: 'ma-expiry', ph: 'With your RN, before the bedside', kind: 'say', to: 'rn', t: 'Read the expiry date out loud AND interpret it',
      cue: 'Say the date, then say what it means. “07/2027” = good until the END of July 2027. Repackaged with only a dispensing date = no more than 12 months from dispensing.',
      line: 'It expires the end of July 2027, so it’s in date.', keys: [['expir', 'expiry', 'use by', 'exp'], ['in date', 'okay', 'fine', 'not expired', 'still good', 'valid']],
      lines: ['ma.a8'], src: ['vid-ma', '16:55'],
      trap: '“Check AND interpret.” Reading the date isn’t enough. Say whether it’s in date.' },
    { id: 'ma-prep', ph: 'With your RN, before the bedside', kind: 'do', t: 'Pop it into the cup, no touching (checks 2 and 3)',
      cue: 'Push the tablet(s) from the blister straight into the medicine cup. Don’t touch them. Check the label against the chart again, and once more before putting the pack away. Get a glass of water.',
      line: 'I’m not touching the tablet, just popping it out into the cup. And a glass of water.',
      lines: ['ma.a10', 'ma.a3', 'ma.a11'], src: ['vid-ma', '17:20'] },

    // ---- at the bedside ----
    { id: 'ma-hh2', ph: 'At the bedside', kind: 'do', t: 'Knock, and hand hygiene on the way in',
      cue: 'Knock. Clean hands before you touch him or his things.', lines: ['ma.a10'], src: ['vid-ma', '17:28'] },
    { id: 'ma-greet', ph: 'At the bedside', kind: 'say', to: 'pt', t: 'Greet + introduce you AND your RN (AI2DET)',
      cue: 'Acknowledge him, Introduce yourself and your RN, say what you’ve brought.',
      line: 'Good morning Mr Luke. My name’s ___, I’m a student nurse from MIT, and this is my preceptor ___, who I’m working with today. I’ve got your {generic}, which is a new medicine for you, I believe.',
      keys: [['my name', 'name is', 'im '], ['student'], ['preceptor', 'working with', 'nurse']], lines: ['ma.e5'], src: ['vid-ma', '17:28'] },
    { id: 'ma-id', ph: 'At the bedside', kind: 'say', to: 'pt', t: 'ID: he says name + DOB, you check the band + NHI',
      cue: 'He TELLS you his full name and date of birth. You read the wristband (name, DOB, NHI) against the chart.',
      line: 'Can I just check I’ve got the right person? Can you tell me your full name and date of birth? And can I have a little look at your wristband?',
      keys: [['name'], ['date of birth', 'birthday', 'born'], ['wristband', 'band', 'bracelet', 'wrist']], lines: ['ma.a1'], src: ['vid-ma', '18:43'] },
    { id: 'ma-id-pt', ph: 'At the bedside', kind: 'pt', t: 'Mr Luke answers', line: 'John Luke. Sixteenth of December, 1942.', src: ['vid-ma', '18:43'] },
    { id: 'ma-allergy', ph: 'At the bedside', kind: 'say', to: 'pt', t: 'Ask about allergies AND bad reactions',
      cue: 'The chart was checked. Now ask HIM: every time, every drug.',
      line: 'Are you allergic to anything that you know of? And have you had a bad reaction to any medicines before?',
      keys: [['allerg'], ['reaction', 'medicine', 'medication']], lines: ['ma.a9'], src: ['vid-ma', '18:43'],
      trap: 'Chart AND verbal. A tick on the chart doesn’t replace asking him.' },
    { id: 'ma-allergy-pt', ph: 'At the bedside', kind: 'pt', t: 'Mr Luke answers', line: 'No, not that I know of.', src: ['vid-ma', '18:43'] },
    { id: 'ma-ask', ph: 'At the bedside', kind: 'say', to: 'pt', t: 'ASK: what does he already know?',
      cue: 'An open question about what he knows. No yes/no questions.',
      line: 'Have you heard of {generic} before? What do you know about it?', keys: [['heard', 'know', 'tell me', 'used']],
      lines: ['ma.e1'], src: ['vid-ma', '18:43'] },
    { id: 'ma-ask-pt', ph: 'At the bedside', kind: 'pt', t: 'Mr Luke answers', line: 'No, I don’t think so. The doctor just said it was a new one.', src: ['tool', 'patient reply'] },
    { id: 'ma-build', ph: 'At the bedside', kind: 'say', to: 'pt', t: 'BUILD: what it’s for, how to take it, side effects, what to do',
      cue: 'PLAIN words, no jargon. What it’s for ({indicationPlain}). How to take it. The common side effects and what to DO about them. Pause and let him think.',
      line: 'This is {generic}. It’s {indicationPlain}. {adversePlain}',
      keys: [['{generic1}', 'this tablet', 'this medicine'], ['for', 'help'], ['ring', 'bell', 'let us know', 'tell us', 'side effect']], lines: ['ma.e2', 'ma.k1', 'ma.k2', 'ma.k3', 'ma.a7'], src: ['vid-ma', '19:30'],
      trap: 'Joan’s RN stopped the student at “resistance”: say it in words he’d use.' },
    { id: 'ma-check', ph: 'At the bedside', kind: 'say', to: 'pt', t: 'CHECK: teach-back in his own words',
      cue: 'Not “Do you understand?” Ask him to tell you back. If he misses a bit, prompt kindly and re-explain. It’s on you, not him.',
      line: 'I want to check I’ve been clear. Can you tell me, in your own words, {checkBack}?',
      keys: [['own words', 'tell me', 'explain', 'what would you do', 'check ive been clear', 'clear']], lines: ['ma.e3'], src: ['deck-ma2', 'slides 25–28'] },
    { id: 'ma-check-pt', ph: 'At the bedside', kind: 'pt', t: 'Mr Luke answers', line: '{ptCheck}', src: ['tool', 'patient reply'] },
    { id: 'ma-consent', ph: 'At the bedside', kind: 'say', to: 'pt', t: 'Consent + questions (right to refuse)',
      cue: 'A real choice. Then invite questions.',
      line: 'Are you happy to take it? Have you got any questions?', keys: [['happy', 'okay to take', 'would you like', 'agree', 'consent'], ['question']],
      lines: ['ma.a6'], src: ['vid-ma', '22:44'] },
    { id: 'ma-consent-pt', ph: 'At the bedside', kind: 'pt', t: 'Mr Luke answers', line: 'Sure, that was pretty clear. Thank you.', src: ['vid-ma', '22:44'] },
    { id: 'ma-give', ph: 'At the bedside', kind: 'do', t: 'Give it: sitting up, with water, watch it go down',
      cue: 'Sitting upright. Hand him the cup and the water. {takeIt} Stay until it’s swallowed. Never leave it on the table.',
      lines: ['ma.a5', 'ma.a11'], src: ['tool', 'oral route basics'] },
    { id: 'ma-routine', ph: 'At the bedside', kind: 'say', to: 'pt', t: 'One practical tip for home',
      cue: 'Joan’s student added routine and refills: the same time each day, and get a repeat before you run out.',
      line: 'It’s best to take it at the same time each day. And when you get down to about a week’s supply, ask your GP for a repeat, so you don’t run out.',
      keys: [['same time', 'every day', 'routine', 'run out', 'repeat']], lines: ['ma.e2'], src: ['vid-ma', '22:44'] },
    { id: 'ma-safe', ph: 'At the bedside', kind: 'say', to: 'pt', t: 'Leave him safe: call bell, thank him',
      cue: 'Call bell within reach. If dizziness is a risk, ask him to ring before getting up. Thank him.',
      line: 'Here’s your call bell. If you want to get up in the next hour or so, give it a ring first so one of us can be with you. Thank you, Mr Luke.',
      keys: [['bell', 'buzzer', 'call'], ['thank']], lines: ['ma.a11', 'ma.e5'], src: ['vid-ma', '20:44'] },
    { id: 'ma-hh3', ph: 'At the bedside', kind: 'do', t: 'Hand hygiene', cue: 'On the way out.', lines: ['ma.a10'], src: ['rub-ma', 'infection control'] },

    // ---- document & debrief ----
    { id: 'ma-doc', ph: 'Document and debrief', kind: 'do', t: 'Sign it on the chart: date, time, dose, Giv/Chck',
      cue: 'In the administration record for THIS drug: date · time (24-hour) · dose WITH units ({dose}, never a bare number) · your initials in Giv, your RN’s in Chck. Only AFTER he’s taken it.',
      lines: ['ma.d1', 'ma.d2', 'ma.d3'], src: ['vid-ma', '06:38'],
      trap: 'Never sign before it’s given. And “1” or “47.5” alone is wrong. Write the unit.' },
    { id: 'ma-abc-rn', ph: 'Document and debrief', kind: 'rn', t: 'Your RN asks', line: 'Can you describe to me how you used the three steps of patient education just now?', src: ['brief-ma', 'Assessment Structure 4'] },
    { id: 'ma-abc', ph: 'Document and debrief', kind: 'say', to: 'rn', t: 'Describe Ask, Build, Check to the RN',
      cue: 'Name each step and what YOU did in it.',
      line: 'First I ASKED what he already knew about {generic}. Then I BUILT on that: I explained what it’s for and the side effects in plain words. Then I CHECKED he understood by asking him to tell me back in his own words.',
      keys: [['ask'], ['build', 'built'], ['check']], lines: ['ma.e4'], src: ['brief-ma', 'Assessment Structure 4'] },
    { id: 'ma-thanks', ph: 'Document and debrief', kind: 'say', to: 'rn', t: 'Thank your RN', line: 'Thank you.', keys: [['thank']], lines: ['ma.e5'], src: ['vid-vs', '17:03'] },
  ];

  /* ---------- curveballs ----------
     Inserted after step `at`. The patient or RN says something; you pick (or say) the safe response.
     opts[0] is the right one (shuffled when shown). */
  const CURVE = [
    // vital signs
    { id: 'cb-vs-band', run: 'vs', at: 'vs-band', who: 'do', title: 'The wristband says 16/12/1943. The chart says 1942.',
      opts: ['Stop. Don’t do the obs on this chart. Tell your preceptor so the ID is sorted first.', 'Carry on. The name and NHI both match, so one wrong digit in the year is just a typo.', 'Ask him which year is right, then correct the chart yourself so the two match up.', 'Do the obs now so he isn’t kept waiting, then mention the mismatch at the end.'],
      why: 'Name, DOB and NHI must ALL match. A mismatch means you can’t be sure it’s the right patient or chart.', lines: ['vs.i3'], src: ['rub-vs', 'Identifies correct patient'] },
    { id: 'cb-vs-consent', run: 'vs', at: 'vs-consent', who: 'pt', line: 'Do you have to? I’m really tired. Can it wait?',
      opts: ['Explain why it matters, offer to come back soon, respect his answer, and tell your preceptor.', 'Tell him kindly that obs are compulsory in hospital, then start while he rests.', 'Let him sleep, and copy his last set of obs into today’s column so the chart isn’t left blank.', 'Do the whole set as fast as you can, without explaining, so he can sleep sooner.'],
      why: 'Consent is a rubric line. A “no” or “not now” is respected, explained, and reported. Never charted as if done.', lines: ['vs.i5', 'vs.e4'], src: ['rub-vs', 'Gain consent'] },
    { id: 'cb-vs-irreg', run: 'vs', at: 'vs-pulse', who: 'do', title: 'His pulse feels irregular.',
      opts: ['Count for a full 60 seconds, note it’s irregular, and report it.', 'Count for 30 seconds and double it, the same as for any adult.', 'Count for 15 seconds and multiply by 4, so it stays quick for him.', 'Ask him to walk around the room, then recheck it once he’s resting.'],
      why: 'Janine’s slide: 30 seconds × 2 UNLESS irregular, then a full minute.', lines: ['vs.i7', 'vs.e2'], src: ['deck-vs', 'slide 23'] },
    { id: 'cb-vs-temp', run: 'vs', at: 'vs-temp', who: 'do', title: 'The thermometer reads 38.3 °C.',
      opts: ['Recheck it, chart it, and report it to your preceptor as abnormal (normal 36.5–37.5).', 'Chart it, and if he looks well, leave it for the next set of obs to see if it settles.', 'Retake it in the other ear until you get a normal reading, then chart that one.', 'Hold off charting it until you’ve rechecked in an hour, so the chart stays accurate.'],
      why: 'Over 38 is pyrexia. Recheck, document at the time, report straight away.', lines: ['vs.e1', 'vs.e2'], src: ['deck-vs', 'slides 30–31'] },
    { id: 'cb-vs-cuff', run: 'vs', at: 'bp-size', who: 'do', title: 'The cuff’s range lines don’t cover his arm. It’s too small.',
      opts: ['Swap to the larger cuff before you start, and check its range lines fit.', 'Use it anyway, then take about 10 off the systolic to allow for it.', 'Wrap the small one a bit tighter so the velcro holds and it fits.', 'Put it on his forearm instead, where the small cuff fits properly.'],
      why: 'A cuff that’s too small reads falsely HIGH. In the demo, Janine brought the larger cuff for Mr Luke.', lines: ['vs.a2', 'vs.i9'], src: ['vid-vs', '01:00'] },
    { id: 'cb-vs-nosound', run: 'vs', at: 'bp-s2b', who: 'do', title: 'Step 2: the needle is falling and you can’t hear anything.',
      opts: ['Let it all down, check the earpieces and chest piece, wait 30–60 s, then redo both steps.', 'Pump straight back up, 20 higher than before, and listen again more carefully.', 'Press the stethoscope harder into his arm so the sound comes through better.', 'Write your step-1 estimate down as the systolic, then just listen out for the diastolic.'],
      why: 'Re-pumping straight away congests the arm and makes the sounds fainter. That’s the retry spiral. Reset, fix the kit, wait, redo.', lines: ['vs.i9'], src: ['pp', 'two-step method'] },
    { id: 'cb-vs-highbp', run: 'vs', at: 'bp-tell', who: 'do', title: 'You get 168/98.',
      opts: ['Stay calm with him, let him rest, recheck it, chart it, and report it to your preceptor.', 'Reassure him that lots of older people run a bit high, chart it, and move on to the next obs.', 'Chart 140/90, the top of normal, since he was probably anxious about the cuff.', 'Leave it for tomorrow’s obs to see if it’s still high before worrying anyone.'],
      why: 'Abnormal = recheck + document + report. That’s exactly the RN’s question in the demo.', lines: ['vs.e1', 'vs.e2'], src: ['vid-vs', '12:33'] },
    // med admin
    { id: 'cb-ma-wrongnhi', run: 'ma', at: 'ma-id', who: 'do', title: 'The NHI on his wristband is DGY 2936. The chart says DGY 2963.',
      opts: ['Stop. Don’t give it. Tell your RN. Identity has to be confirmed first.', 'Give it. His name and date of birth both match, and that’s two identifiers.', 'Correct the chart so it matches his wristband, then carry on with the dose.', 'Ask him to tell you his NHI, and go with whichever number he says.'],
      why: 'Right patient = verbal AND wristband, including the NHI, all matching the chart.', lines: ['ma.a1'], src: ['deck-ma1', 'slide 27'] },
    { id: 'cb-ma-allergy', run: 'ma', at: 'ma-allergy', who: 'pt', line: '{allergyLine}',
      opts: ['Don’t give it. Tell your RN so it’s checked and added to the yellow allergies box.', 'Give it. The chart says no allergies, and the prescriber has signed and dated that box.', 'Give half the usual dose this time, and watch him closely for any reaction.', 'Give it as charted, then write the reaction in his notes after the round.'],
      why: 'An allergy to a medicine is a contraindication (Joan, slide 43). The chart can be out of date. That’s why you ask every time.', lines: ['ma.a9'], src: ['deck-ma1', 'slide 43'] },
    { id: 'cb-ma-expired', run: 'ma', at: 'ma-expiry', who: 'do', title: 'The pack says EXP 05/2026. Today is in October 2026.',
      opts: ['Expired: don’t use it. Get an in-date pack and return this one.', 'It’s only a few months out of date, so it will still work fine today.', 'Use it for today’s dose and let pharmacy know about it later on.', '05/2026 means it’s good for twelve months, so until May 2027.'],
      why: '05/2026 = good until the end of May 2026. That’s past. “Check & interpret” is a rubric line.', lines: ['ma.a8'], src: ['deck-ma1', 'slide 42'] },
    { id: 'cb-ma-expiry-ok', run: 'ma', at: 'ma-expiry', who: 'do', title: 'The pack says EXP 10/2026, and today is in October 2026.',
      opts: ['In date: a month-only date is good until the END of October 2026.', 'Expired: a month-only date runs out at the START of that month.', 'Can’t tell without a day on it, so don’t use it, to be safe.', 'Expired, because stock can’t be used in its final month.'],
      why: 'Month only = the end of that month (Joan, slide 42).', lines: ['ma.a8'], src: ['deck-ma1', 'slide 42'] },
    { id: 'cb-ma-refuse', run: 'ma', at: 'ma-consent', who: 'pt', line: 'Actually, I don’t want any more pills today.',
      opts: ['Ask why, explain what it’s for, respect his choice, then tell your RN and chart code R.', 'Keep gently encouraging him until he agrees, because it’s a new medicine he really needs.', 'Leave it in the cup on his table so he can take it later when he feels like it.', 'Mix it into his breakfast so he still gets the dose without having to agree.'],
      why: 'Right to refuse: explain the consequences, document the reason, inform the RN, and discard (don’t store) the refused dose (Joan, slide 39).', lines: ['ma.a6'], src: ['deck-ma1', 'slide 39'] },
    { id: 'cb-ma-para-last', run: 'ma', drug: 'para', at: 'ma-time', who: 'do', title: 'The administration record shows 1 g given at 1000. It’s now 1130.',
      opts: ['Not due: under 4 hours. Don’t give it. Check the timing with your RN.', 'Give it. qid just means four doses a day, at whatever times suit him.', 'Give half now and the other half in a couple of hours to space it out.', 'Give it now and push his next dose back a couple of hours to make up.'],
      why: 'Right time includes when the last dose was given. Paracetamol needs at least 4 hours between doses.', lines: ['ma.a4'], src: ['ds-para', '4.2'] },
    { id: 'cb-ma-para-otc', run: 'ma', drug: 'para', at: 'ma-allergy', who: 'pt', line: 'Oh, I took a couple of my own Panadol this morning for my back.',
      opts: ['Hold it and tell your RN: with his charted 1 g qid, that pushes him over 4 g in 24 hours.', 'Give it. Panadol is a brand-name painkiller, so it isn’t the same as paracetamol.', 'Give it now, and cross off tonight’s 2200 dose yourself so the day evens out.', 'Give it. Two extra tablets this morning won’t make a difference at his weight.'],
      why: 'Panadol IS paracetamol. Max 4 g in 24 h. Too much harms the liver (data sheet 4.4).', lines: ['ma.a4', 'ma.a11'], src: ['ds-para', '4.2, 4.4'] },
    { id: 'cb-ma-meto-low', run: 'ma', drug: 'meto', at: 'ma-time', who: 'rn', line: 'His obs this morning: pulse 52, BP 96 over 58.',
      opts: ['Withhold it and discuss with the RN. A beta blocker slows the heart and lowers BP further.', 'Give it. It’s charted daily, and missing even one dose is what pushes his BP back up again.', 'Give him half the tablet today, so he gets some of the effect but less of it.', 'Give it as charted, and recheck his pulse and BP at tomorrow’s morning obs.'],
      why: 'Check pulse and BP before a beta blocker. Bradycardia is a common adverse effect (data sheet 4.8).', lines: ['ma.k3', 'ma.a11'], src: ['ds-meto', '4.4, 4.8'] },
    { id: 'cb-ma-meto-crush', run: 'ma', drug: 'meto', at: 'ma-consent', who: 'pt', line: 'I struggle with big tablets. Can you crush it up for me?',
      opts: ['Don’t crush it (it’s controlled release). It can be halved. Ask the RN or pharmacist.', 'Crush it into a spoonful of yoghurt, which is how many older people take tablets.', 'Let him chew it up first, since chewing gives the same dose as swallowing it.', 'Dissolve it in a little water and give it as a drink, which is gentler to swallow.'],
      why: 'Controlled release: swallow whole. Halving is OK, crushing or chewing is not (Healthify). Joan: check with a pharmacist before crushing.', lines: ['ma.a5', 'ma.a11'], src: ['deck-ma1', 'slide 30'] },
    { id: 'cb-ma-jargon', run: 'ma', at: 'ma-build', who: 'rn', line: 'Is there another way you could explain that to him, without the medical words?',
      opts: ['Say it again in everyday words he’d use himself, then check it made sense to him.', 'Repeat the same sentence again, just more slowly and a little bit louder.', 'Tell him it’s quite technical, and that the doctor can explain it all properly later.', 'Hand him the printed data sheet so he can read the full details for himself.'],
      why: 'Build = appropriate terms. In Joan’s role play the RN stopped the student at “resistance” and asked for another way to say it.', lines: ['ma.e2'], src: ['vid-ma', '20:03'] },
  ];

  /* ---------- per-drug fill-ins used by {placeholders} ---------- */
  const FILL = {
    para: {
      generic: 'paracetamol', generic1: 'paracetamol', order: 'Paracetamol 1 g PO qid', dose: '1 g', strength: 'paracetamol 500 mg tablets',
      tabs: 'two 500 mg tablets', freqShort: 'four times a day (qid)', klassShort: 'simple analgesic', indication: 'his recurrent backache',
      indKey: 'back', aeKey: 'liver', adverseShort: 'very rare at the right dose: allergic rash, and liver damage if too much is taken',
      considerShort: 'I’ll check it’s been at least 4 hours since his last dose and that he hasn’t had other paracetamol, because the max is 4 grams a day.',
      indicationPlain: DRUGS.para.indicationPlain, adversePlain: DRUGS.para.adversePlain, checkBack: DRUGS.para.checkBack, takeIt: DRUGS.para.takeIt,
      lastDose: DRUGS.para.lastDose, ptCheck: 'It’s for my back pain, and if I get a rash or feel funny I ring the bell. And I don’t take any of my own Panadol.',
      allergyLine: 'Panadol? Oh, I came out in a nasty rash after Panadol once.',
    },
    meto: {
      generic: 'metoprolol succinate', generic1: 'metoprolol', order: 'Metoprolol Succinate CR 47.5 mg PO daily', dose: '47.5 mg', strength: 'metoprolol succinate CR 47.5 mg',
      tabs: 'one 47.5 mg CR tablet', freqShort: 'once daily', klassShort: 'beta-adrenoceptor blocker', indication: 'his high blood pressure and his heart failure',
      indKey: 'pressure', aeKey: 'brady', adverseShort: 'tiredness, bradycardia, dizziness especially on standing, and cold hands and feet',
      considerShort: 'I’ll check his pulse and blood pressure first, and he’s a falls risk because of the dizziness.',
      indicationPlain: DRUGS.meto.indicationPlain, adversePlain: DRUGS.meto.adversePlain, checkBack: DRUGS.meto.checkBack, takeIt: DRUGS.meto.takeIt,
      lastDose: DRUGS.meto.lastDose, ptCheck: 'It’s for my blood pressure and my heart, and if I feel dizzy I ring the bell before I get up.',
      allergyLine: 'Metoprolol? I was on a beta blocker years ago and I came out in hives.',
    },
  };

  window.CLS_DATA = { SRC, RUBRIC, PATIENT, NORMALS, DRUGS, STEPS: { vs: VS, ma: MA }, CURVE, FILL };
})();
