/* rnq-data.js — "The RN asks…": the questions an assessor/RN can put to you during either practical.
   a = the SHORT model answer (one fact a line). opts[0] is right (shuffled on screen; length-gated by tests/check.mjs).
   keys = what the mic listens for when you answer out loud. src = where the answer comes from. */
(function () {
  'use strict';
  const Q = [
    /* ===================== VITAL SIGNS: normal ranges ===================== */
    { id: 'r-temp', run: 'vs', topic: 'Normal ranges', q: 'What’s the normal adult temperature range?',
      a: '36.5 to 37.5 °C.', keys: [['36.5', '36 point 5', 'thirty six point five'], ['37.5', '37 point 5', 'thirty seven point five']],
      opts: ['36.5 to 37.5 °C', '36.0 to 37.0 °C', '35.5 to 37.5 °C', '37.0 to 38.0 °C'], src: ['deck-vs', 'slide 30'] },
    { id: 'r-hr', run: 'vs', topic: 'Normal ranges', q: 'What’s a normal adult heart rate?',
      a: '60 to 100 beats per minute.', keys: [['60', 'sixty'], ['100', 'hundred']],
      opts: ['60 to 100 bpm', '50 to 90 bpm', '70 to 110 bpm', '60 to 120 bpm'], src: ['vid-vs', '11:42'] },
    { id: 'r-rr', run: 'vs', topic: 'Normal ranges', q: 'What’s a normal adult respiratory rate?',
      a: '12 to 20 breaths per minute.', keys: [['12', 'twelve'], ['20', 'twenty']],
      opts: ['12 to 20 breaths/min', '10 to 16 breaths/min', '16 to 24 breaths/min', '8 to 18 breaths/min'], src: ['deck-vs', 'slide 10'] },
    { id: 'r-bp', run: 'vs', topic: 'Normal ranges', q: 'What are the normal systolic and diastolic ranges?',
      a: 'Systolic 110 to 140.\nDiastolic 60 to 90 mmHg.', keys: [['110', 'one ten', 'hundred and ten'], ['140', 'one forty', 'hundred and forty'], ['60', 'sixty'], ['90', 'ninety']],
      opts: ['110–140 over 60–90 mmHg', '100–120 over 50–70 mmHg', '120–160 over 70–100 mmHg', '90–130 over 60–80 mmHg'], src: ['deck-vs', 'slide 17'] },
    { id: 'r-spo2', run: 'vs', topic: 'Normal ranges', q: 'What’s a normal adult oxygen saturation?',
      a: '95 to 100 %.', keys: [['95', 'ninety five'], ['100', 'hundred']],
      opts: ['95 to 100 %', '90 to 100 %', '92 to 98 %', '85 to 95 %'], src: ['deck-vs', 'slide 13'] },
    { id: 'r-brady', run: 'vs', topic: 'Normal ranges', q: 'What do bradycardia and tachycardia mean, in numbers?',
      a: 'Bradycardia: under 60.\nTachycardia: over 100.', keys: [['60', 'sixty'], ['100', 'hundred']],
      opts: ['Brady under 60, tachy over 100', 'Brady under 50, tachy over 120', 'Brady under 70, tachy over 90', 'Brady under 40, tachy over 110'], src: ['deck-vs', 'slide 24'] },
    { id: 'r-rr32', run: 'vs', topic: 'Normal ranges', q: 'An adult has a regular respiratory rate of 32. What’s the term?',
      a: 'Tachypnoea: regular but over 20.', keys: [['tachypnoea', 'tachypnea', 'tachy']],
      opts: ['Tachypnoea', 'Bradypnoea', 'Hyperventilation', 'Cheyne-Stokes'], src: ['quiz-vs', 'Q3'] },
    { id: 'r-pyrexia', run: 'vs', topic: 'Normal ranges', q: 'What counts as a low-grade fever, and as pyrexia?',
      a: 'Low-grade: 37.6 to 37.9 °C.\nPyrexia: over 38 °C.', keys: [['37.6', '37 point 6', 'thirty seven point six', 'low grade'], ['38', 'thirty eight']],
      opts: ['Low-grade 37.6–37.9; pyrexia over 38', 'Low-grade 37.0–37.5; pyrexia over 37.6', 'Low-grade 38.0–38.4; pyrexia over 39', 'Low-grade 37.5–38.5; pyrexia over 40'], src: ['deck-vs', 'slides 30–31'] },
    { id: 'r-hypo', run: 'vs', topic: 'Normal ranges', q: 'What temperature is hypothermia?',
      a: 'Below 35 °C.', keys: [['35', 'thirty five']],
      opts: ['Below 35 °C', 'Below 36 °C', 'Below 36.5 °C', 'Below 34 °C'], src: ['deck-vs', 'slide 32'] },

    /* ===================== VITAL SIGNS: technique ===================== */
    { id: 't-count', run: 'vs', topic: 'Technique', q: 'How long do you count the pulse and respirations for?',
      a: '30 seconds and double it.\nA full minute if it’s irregular.', keys: [['30', 'thirty'], ['minute', 'irregular', '60']],
      opts: ['30 s × 2, or a full minute if irregular', '15 s × 4, or 30 s × 2 if irregular', 'Always a full minute, whatever the rhythm', '30 s × 2, or 15 s × 4 if irregular'], src: ['deck-vs', 'slides 9, 23'] },
    { id: 't-resp', run: 'vs', topic: 'Technique', q: 'Why don’t you tell him you’re counting his breathing?',
      a: 'People change their breathing when they know.\nI count while my fingers stay on his pulse.', keys: [['change', 'aware', 'alter', 'know']],
      opts: ['Knowing changes his breathing, so I count with my fingers still on his pulse.', 'It’s faster not to explain, and the rubric doesn’t ask me to tell him.', 'It might worry him, so I only tell him if the number is abnormal.', 'Respirations don’t need consent, because nothing touches him.'], src: ['deck-vs', 'slide 9'] },
    { id: 't-tymp', run: 'vs', topic: 'Technique', q: 'Talk me through the tympanic temperature.',
      a: 'New probe cover.\nGently pull the top of the ear up and back.\nProbe in snugly, press, read, eject the cover.', keys: [['cover'], ['up and back', 'pull', 'ear']],
      opts: ['New cover, ear up and back, probe in snugly, read, eject the cover', 'Same cover as last time, ear down and forward, probe in lightly, read', 'No cover needed, pull the lobe down, hold for a minute, then read it', 'New cover, probe under the tongue for a minute, then read and eject'], src: ['pp', 'tympanic technique'] },
    { id: 't-when', run: 'vs', topic: 'Technique', q: 'When do we take vital signs?',
      a: 'On admission and to monitor.\nBefore, during and after some medications.\nAfter procedures, and whenever the patient’s condition changes.', keys: [['admission', 'admitted'], ['change', 'deteriorat', 'medication', 'procedure', 'surgery']],
      opts: ['Admission, monitoring, around some meds, after procedures, any change', 'Only on admission and at discharge, unless the doctor asks for any more', 'Once each shift, at the same times, whatever the patient’s condition', 'Only when the patient complains of feeling unwell or asks for them'], src: ['deck-vs', 'slide 4'] },

    /* ===================== VITAL SIGNS: two-step BP ===================== */
    { id: 'b-why', run: 'vs', topic: 'Two-step BP', q: 'Why do you do the palpation step first?',
      a: 'To estimate the systolic,\nso I know how high to pump for step 2:\nnot too low (I’d miss the first sound), not too high (it hurts).', keys: [['estimate', 'approximate', 'roughly'], ['systolic', 'how high', 'pump']],
      opts: ['To estimate the systolic, so I know how high to pump in step 2', 'To find the diastolic first, so I know where to stop listening', 'To warm the arm up, so the sounds are louder in step 2', 'To check his pulse rate, so I can chart it at the same time'], src: ['pp', 'two-step rationale'] },
    { id: 'b-high', run: 'vs', topic: 'Two-step BP', q: 'In step 2, how high do you pump the cuff?',
      a: '30 mmHg above the estimated systolic.\n(Demo: about 110, so pump to 140.)', keys: [['30', 'thirty'], ['above', 'over', 'estimate', 'plus']],
      opts: ['30 mmHg above the estimate', '10 mmHg above the estimate', 'Always to 200 mmHg', 'Exactly to the estimate'], src: ['vid-vs', '09:04'] },
    { id: 'b-wait', run: 'vs', topic: 'Two-step BP', q: 'What do you do between step 1 and step 2?',
      a: 'Let ALL the air out.\nWait 30 seconds before pumping again.', keys: [['30', 'thirty', 'wait'], ['deflate', 'all the air', 'let it down', 'release', 'down']],
      opts: ['Deflate fully, then wait 30 seconds', 'Keep it half up so step 2 is quicker', 'Pump straight back up, no waiting', 'Wait 5 minutes with the cuff still up'], src: ['pp', 'deflate fully, wait 30 s'] },
    { id: 'b-rate', run: 'vs', topic: 'Two-step BP', q: 'How fast do you let the cuff down?',
      a: '2 to 3 mmHg per second.', keys: [['2', 'two'], ['3', 'three'], ['second']],
      opts: ['2–3 mmHg per second', '5–10 mmHg per second', '1 mmHg every 5 seconds', 'As fast as the valve allows'], src: ['pp', 'deflation rate'] },
    { id: 'b-sounds', run: 'vs', topic: 'Two-step BP', q: 'Which sound is the systolic, and which is the diastolic?',
      a: 'Systolic: the FIRST clear sound.\nDiastolic: where the sound DISAPPEARS.', keys: [['first'], ['disappear', 'last', 'stop', 'gone']],
      opts: ['Systolic is the first sound; diastolic is where it disappears', 'Systolic is the loudest sound; diastolic is the first one', 'Systolic is the last sound; diastolic is the first one', 'Systolic is where it gets muffled; diastolic is the loudest one'], src: ['deck-vs', 'slide 17'] },
    { id: 'b-name', run: 'vs', topic: 'Two-step BP', q: 'What are the sounds you hear called?',
      a: 'Korotkoff sounds.', keys: [['korotkoff', 'korotkov', 'korot']],
      opts: ['Korotkoff sounds', 'Bowel sounds', 'Heart sounds S1 and S2', 'Stridor sounds'], src: ['deck-vs', 'slide 16'] },
    { id: 'b-steth', run: 'vs', topic: 'Two-step BP', q: 'In step 2, when does the stethoscope go on?',
      a: 'BEFORE I pump.\nChest piece on the brachial artery first, then inflate.', keys: [['before'], ['pump', 'inflate']],
      opts: ['Before I pump: on the brachial first, then inflate', 'After I’ve pumped up to the target pressure', 'Halfway through pumping, once the radial pulse has gone', 'Only once I start letting the air back out'], src: ['pp', 'auscultation'] },
    { id: 'b-small', run: 'vs', topic: 'Two-step BP', q: 'What happens if the cuff is too small?',
      a: 'It reads falsely HIGH.\nSwap to the right size (the larger cuff for Mr Luke).', keys: [['high', 'higher', 'over']],
      opts: ['It reads falsely high, so I swap to the right size', 'It reads falsely low, so I add 10 to the systolic', 'Nothing changes, as long as I wrap it tightly', 'It only changes the diastolic, so the systolic is fine'], src: ['vid-vs', '01:00'] },
    { id: 'b-arm', run: 'vs', topic: 'Two-step BP', q: 'How should his arm and body be positioned?',
      a: 'Arm bare, supported at heart level, palm up.\nSitting, feet flat, not talking.', keys: [['heart level', 'heart'], ['support', 'rest', 'palm']],
      opts: ['Arm bare, supported at heart level; sitting, feet flat, not talking', 'Arm hanging down by his side, so the blood fills the brachial artery', 'Arm raised above his head, sleeve rolled down, and chatting to relax', 'Lying flat, arm across his chest, legs crossed for comfort'], src: ['pp', 'positioning'] },
    { id: 'b-nosound', run: 'vs', topic: 'Two-step BP', q: 'You can’t hear anything. What do you do?',
      a: 'Let it all down.\nCheck earpieces forward and the chest piece open (tap it).\nRest it lightly on the brachial, wait, then redo both steps.', keys: [['down', 'deflate', 'release'], ['earpiece', 'chest piece', 'tap', 'diaphragm', 'bell'], ['wait', 'redo', 'again', 'repeat']],
      opts: ['Deflate, check earpieces and chest piece, wait, then redo both steps', 'Pump straight back up higher and listen again more carefully', 'Press the stethoscope much harder into the inside of his elbow', 'Chart the step-1 estimate and leave the diastolic blank'], src: ['pp', 'troubleshooting'] },

    /* ===================== VITAL SIGNS: charting, reporting, escalation ===================== */
    { id: 'd-how', run: 'vs', topic: 'Charting and reporting', q: 'How do you chart temperature, heart rate, resps and BP?',
      a: 'Temp and HR: an X.\nRR: the actual number in the box.\nBP: arrows onto the systolic and diastolic lines, joined by a dotted line.', keys: [['x', 'cross'], ['number', 'box'], ['arrow']],
      opts: ['Temp and HR an X; RR the number; BP arrows joined by a dotted line', 'Everything as a dot, joined into one line across the whole chart', 'Write all four numbers in the notes, then copy them onto the chart', 'Temp and RR an X; HR the number; BP as two dots on the same line'], src: ['vid-vs', '16:16–17:03'] },
    { id: 'd-rules', run: 'vs', topic: 'Charting and reporting', q: 'What are the rules for documenting vital signs?',
      a: 'Document at the time, never on a paper towel or your hand.\nDate and 24-hour time; blue or black pen.\nErrors: one line through, still readable.', keys: [['at the time', 'straight away', 'directly', 'immediately'], ['24', 'twenty four', 'date', 'pen', 'line']],
      opts: ['At the time, date and 24-hour time, blue/black pen, one-line errors', 'At the end of the shift, from notes written on a paper towel', 'In pencil first, so mistakes can be rubbed out before signing', 'Whenever there’s a spare moment, in any pen that is handy'], src: ['deck-vs', 'slide 33'] },
    { id: 'd-abn', run: 'vs', topic: 'Charting and reporting', q: 'What’s your responsibility if any observation is outside the normal range?',
      a: 'Recheck it.\nReport it to my preceptor/RN straight away.', keys: [['report', 'tell', 'let you know', 'inform'], ['recheck', 'check again', 'repeat', 'double check']],
      opts: ['Recheck it and report it to the RN straight away', 'Chart it and mention it at the end of the shift', 'Wait for the next set of obs to see if it settles', 'Tell the patient first, then decide if it matters'], src: ['vid-vs', '12:33'] },
    { id: 'd-ews', run: 'vs', topic: 'Charting and reporting', q: 'What’s the early warning score for?',
      a: 'Recognising and responding to deterioration.\nThe total triggers escalation, and so does any single value in the red or blue zone.', keys: [['deteriorat', 'worse', 'sicker'], ['escalat', 'respond', 'trigger', 'call']],
      opts: ['Spotting deterioration and triggering escalation', 'Recording the patient’s pain levels each shift', 'Tracking nutrition and fluid intake over the day', 'Showing that observations were done on time'], src: ['deck-vs', 'slides 40–41'] },
    { id: 'd-ewsbp', run: 'vs', topic: 'Charting and reporting', q: 'Which blood pressure value scores on the EWS?',
      a: 'Only the systolic.\nBut you chart both.', keys: [['systolic']],
      opts: ['Only the systolic, but you chart both', 'Only the diastolic, but you chart both', 'Both values, added together', 'The difference between the two'], src: ['deck-vs', 'slide 41'] },
    { id: 'c-ai2det', run: 'both', topic: 'Communication', q: 'What does AI2DET stand for?',
      a: 'Acknowledge, Introduce, Identify,\nDuration, Explanation, Thank you.', keys: [['acknowledge'], ['introduce'], ['identify'], ['duration'], ['explain', 'explanation'], ['thank']],
      opts: ['Acknowledge, Introduce, Identify, Duration, Explanation, Thank you', 'Assess, Inform, Instruct, Document, Evaluate, Treat', 'Ask, Introduce, Inform, Discuss, Educate, Test', 'Acknowledge, Inspect, Identify, Diagnose, Escalate, Thank you'], src: ['deck-ai2det', 'slides 27–33'] },
    { id: 'c-culture', run: 'vs', topic: 'Communication', q: 'How do you show culturally safe practice in this assessment?',
      a: 'Ask how he’d like to be addressed.\nExplain and get consent before touching him.\nRespect his answers; include whānau if he wants.', keys: [['call', 'addressed', 'name', 'prefer'], ['consent', 'permission', 'explain', 'respect']],
      opts: ['Preferred name, explain + consent before touching, respect his choices', 'Use his full formal name every time, whatever he says he prefers', 'Assume he’s fine with touching, since vital signs are routine care', 'Skip the explanation to save time, as long as you are being polite'], src: ['rub-vs', 'Evaluation: culturally safe practices'] },

    /* ===================== MED ADMIN: rights and checks ===================== */
    { id: 'm-rights', run: 'ma', topic: 'Rights and checks', q: 'What are the 8 rights and the 2 checks?',
      a: 'Right patient, medication, dose, time, route,\nright to refuse, right indication, right documentation.\nPlus: check expiry, check allergies.', keys: [['patient'], ['medication', 'drug'], ['dose'], ['time'], ['route'], ['refuse'], ['indication'], ['documentation', 'document'], ['expir'], ['allerg']],
      opts: ['Patient, medication, dose, time, route, refuse, indication, documentation + expiry, allergies', 'Patient, medication, dose, time, route, price, brand, storage + weight, height checks', 'Patient, doctor, pharmacy, dose, time, ward, chart, signature + expiry, allergies', 'Patient, medication, dose, time, route, family, food, sleep + pulse, BP checks'], src: ['deck-ma1', 'slide 23'] },
    { id: 'm-id', run: 'ma', topic: 'Rights and checks', q: 'How do you confirm the right patient?',
      a: 'He tells me his full name and date of birth.\nI check the wristband (name, DOB, NHI) against the chart.', keys: [['name'], ['date of birth', 'birthday', 'birth'], ['wristband', 'band', 'nhi']],
      opts: ['He says name + DOB; I check the band, including NHI, against the chart', 'I say his name and he nods; then I check the room number matches', 'I check the bed number on the chart, then the name above his bed', 'I ask the RN who he is, then check the chart’s name on its own'], src: ['deck-ma1', 'slide 27'] },
    { id: 'm-3checks', run: 'ma', topic: 'Rights and checks', q: 'How many times do you check the medicine against the chart, and when?',
      a: 'Three times:\nwhen I take it from storage, when I prepare it,\nand again before I give it or put the pack back.', keys: [['three', '3'], ['prepar', 'storage', 'before']],
      opts: ['Three: getting it out, preparing it, and before giving/putting it back', 'Once, when I take it out of the drug trolley at the start', 'Twice: once in the drug room and once after he’s swallowed it', 'Only once the RN has checked it, because they sign for it'], src: ['deck-ma1', 'slides 28–29'] },
    { id: 'm-expiry', run: 'ma', topic: 'Rights and checks', q: 'The pack says EXP 07/2027. What does that mean?',
      a: 'It’s good until the END of July 2027.', keys: [['end'], ['july']],
      opts: ['Good until the end of July 2027', 'Good until the start of July 2027', 'Good until 7 days before July 2027', 'Good for 12 months from July 2027'], src: ['deck-ma1', 'slide 42'] },
    { id: 'm-repack', run: 'ma', topic: 'Rights and checks', q: 'The pharmacist repackaged it and there’s only a dispensing date. How long is it good for?',
      a: 'No more than 12 months after the dispensing date.', keys: [['12', 'twelve', 'year'], ['dispens']],
      opts: ['12 months from the dispensing date', '6 months from the dispensing date', 'Until the original pack’s expiry', 'It never expires once it is dispensed'], src: ['deck-ma1', 'slide 42'] },
    { id: 'm-allergy', run: 'ma', topic: 'Rights and checks', q: 'The chart says no allergies. Why ask him anyway?',
      a: 'The tick only means he was asked once.\nAllergies can be new, or remembered later.\nChart AND verbal, every time.', keys: [['new', 'remember', 'change', 'later', 'every time'], ['chart', 'verbal', 'both']],
      opts: ['The tick means he was asked once. Allergies can be new, so: chart AND verbal', 'I don’t need to, because the prescriber has already signed and dated the allergy box', 'Only to be polite, since the chart is always the legal record of allergies', 'Only if he’s on a new drug, because old drugs have already been tested'], src: ['vid-ma', '02:15'] },
    { id: 'm-nkda', run: 'ma', topic: 'Rights and checks', q: 'What does NKDA mean?',
      a: 'No known drug allergies.', keys: [['no known'], ['allerg']],
      opts: ['No known drug allergies', 'No kidney disease apparent', 'Not known, doctor to assess', 'New known drug allergy'], src: ['deck-ma1', 'slide 43'] },
    { id: 'm-refuse', run: 'ma', topic: 'Rights and checks', q: 'What do you do if he refuses?',
      a: 'Ask why and explain the consequences simply.\nRespect his decision.\nDocument the reason (code R), tell the RN, discard the dose.', keys: [['why', 'reason', 'explain'], ['respect', 'document', 'code r', 'tell', 'rn']],
      opts: ['Ask why, explain, respect it; document code R, tell the RN, discard it', 'Keep encouraging him until he takes it, because it’s been prescribed for him', 'Leave it on his table for later, and sign for it as given today', 'Hide it in his food, and record it as given with a note in his file'], src: ['deck-ma1', 'slide 39'] },
    { id: 'm-route', run: 'ma', topic: 'Rights and checks', q: 'The order has no route written. What do you do?',
      a: 'Withhold it and contact the prescriber.', keys: [['withhold', 'hold', 'don’t give', 'not give'], ['prescriber', 'doctor']],
      opts: ['Withhold it and contact the prescriber', 'Give it orally, since that’s the usual', 'Ask the patient how he’d like it', 'Write in the route yourself, then give it'], src: ['deck-ma1', 'slide 36'] },
    { id: 'm-30', run: 'ma', topic: 'Rights and checks', q: 'How close to the scheduled time must a regular medicine be given?',
      a: 'Within 30 minutes of the scheduled time.', keys: [['30', 'thirty'], ['minute']],
      opts: ['Within 30 minutes', 'Within 2 hours', 'Any time that day', 'Within 5 minutes'], src: ['deck-ma1', 'slide 32'] },
    { id: 'm-qid', run: 'ma', topic: 'Rights and checks', q: 'What does qid mean, and what times does the chart suggest?',
      a: 'Four times a day.\n0600, 1200, 1800, 2200.', keys: [['four', '4'], ['0600', '6', 'six', '1200', 'twelve', '2200']],
      opts: ['Four times a day: 0600, 1200, 1800, 2200', 'Once a day, every morning at 0800 only', 'Every 4 hours: 0200, 0600, 1000, 1400, 1800 …', 'Three times a day: 0800, 1400, 2000'], src: ['chart', 'Recommended Administration Times'] },

    /* ===================== MED ADMIN: documentation ===================== */
    { id: 'm-doc', run: 'ma', topic: 'Documentation', q: 'What exactly do you write on the chart, and when?',
      a: 'Straight after he’s taken it:\ndate, 24-hour time, dose WITH units,\nmy initials (Giv) and the RN’s (Chck).', keys: [['date'], ['time'], ['dose', 'unit'], ['initial', 'sign']],
      opts: ['After he takes it: date, 24-h time, dose + units, Giv and Chck initials', 'Before I go in: the time, the drug name and my full signature to save time', 'At the end of the shift: a tick in the box and the RN’s initials only', 'After he takes it: the dose as a bare number, and the RN signs for me'], src: ['vid-ma', '06:38'] },
    { id: 'm-before', run: 'ma', topic: 'Documentation', q: 'Can you sign for it before you give it, to save time?',
      a: 'Never.\nOnly after it has actually been given.', keys: [['never', 'no', 'after']],
      opts: ['Never: only after it’s actually been given', 'Yes, if the RN is watching and agrees to it', 'Yes, as long as you cross it out if he refuses', 'Yes, for regular medicines but never for PRN'], src: ['deck-ma1', 'slide 41'] },
    { id: 'm-codes', run: 'ma', topic: 'Documentation', q: 'On the NMC, what do the codes R and W mean?',
      a: 'R = patient refused.\nW = withheld.', keys: [['refus'], ['withh', 'with held']],
      opts: ['R = refused, W = withheld', 'R = review, W = waiting', 'R = removed, W = wasted', 'R = repeat, W = wrong dose'], src: ['chart', 'Non-administration Codes'] },

    /* ===================== MED ADMIN: Ask, Build, Check ===================== */
    { id: 'e-abc', run: 'ma', topic: 'Ask, Build, Check', q: 'What are the three steps to meeting health literacy needs?',
      a: 'ASK what he already knows.\nBUILD on it in plain words.\nCHECK he understood (teach-back).', keys: [['ask'], ['build'], ['check']],
      opts: ['Ask, Build, Check', 'Assess, Brief, Confirm', 'Ask, Bridge, Clarify', 'Advise, Build, Close'], src: ['deck-ma2', 'slide 16'] },
    { id: 'e-ask', run: 'ma', topic: 'Ask, Build, Check', q: 'Give me an example of an ASK question.',
      a: '“What have you heard about this medicine?”\nOpen, not yes/no.', keys: [['what', 'tell me', 'how'], ['heard', 'know', 'medicine', 'tablet']],
      opts: ['“What have you heard about this medicine?”', '“You know what this is for, don’t you?”', '“Have you taken this one before, yes or no?”', '“Shall I just tell you all about it now?”'], src: ['deck-ma2', 'slide 19'] },
    { id: 'e-build', run: 'ma', topic: 'Ask, Build, Check', q: 'What goes into BUILD?',
      a: 'Link it to what he already knows; use his words.\nPlain language: explain any medical term.\nWhat to expect, side effects, the follow-up plan. Pause.', keys: [['plain', 'simple', 'his words', 'everyday'], ['side effect', 'expect', 'effect']],
      opts: ['Link to what he knows, plain words, effects, side effects, plan, pauses', 'Read the full data sheet aloud, word for word, so that nothing is left out', 'Use the correct medical terms only, so the information stays accurate', 'Give him a printout and let him read it in his own time, no talking'], src: ['deck-ma2', 'slides 21–22'] },
    { id: 'e-check', run: 'ma', topic: 'Ask, Build, Check', q: 'How do you CHECK, and what don’t you say?',
      a: 'Ask him to tell me back in his own words (teach-back).\nDon’t ask “Do you understand?”, and don’t rely on a nod.', keys: [['own words', 'tell me back', 'teach back', 'explain back'], ['understand', 'nod']],
      opts: ['Teach-back in his own words, not “Do you understand?” or a nod', 'Ask “Do you understand?” and wait for him to say yes', 'Give him a short written quiz to fill in and mark it', 'Watch for him nodding, which shows that he understood'], src: ['deck-ma2', 'slides 25–26'] },
    { id: 'e-fail', run: 'ma', topic: 'Ask, Build, Check', q: 'He can’t explain it back. Now what?',
      a: 'It’s on me, not him.\nGo back to BUILD and explain it a different way:\nsimpler words, a picture, or write it down.', keys: [['build', 'again', 'different', 'differently', 're explain', 'explain']],
      opts: ['It’s on me: go back to Build and explain it differently', 'Tell him he wasn’t listening and repeat it word for word', 'Move on, since he’s heard the information once already', 'Note that he lacks capacity, and only teach his whānau'], src: ['deck-ma2', 'slide 29'] },
    { id: 'e-describe', run: 'ma', topic: 'Ask, Build, Check', q: 'Describe to me how you used Ask, Build, Check just now.',
      a: 'I ASKED what he knew about it.\nI BUILT on that in plain words: what it’s for and the side effects.\nI CHECKED by asking him to tell me back in his own words.', keys: [['ask'], ['build', 'built'], ['check']],
      opts: ['I asked what he knew, built on it in plain words, then checked with teach-back', 'I told him everything first, then asked if he had any questions right at the end', 'I checked his chart, built the dose, then asked him to sign the consent form', 'I asked the RN, built a care plan, and checked the drug against the label'], src: ['brief-ma', 'Assessment Structure 4'] },

    /* ===================== THE TWO DRUGS ===================== */
    { id: 'p-name', run: 'ma', drug: 'para', topic: 'Paracetamol', q: 'The pack says Pacimol. What’s the generic name, and what class is it?',
      a: 'Paracetamol.\nAn analgesic (pain reliever; also lowers fever).', keys: [['paracetamol'], ['analgesic', 'pain']],
      opts: ['Paracetamol, an analgesic', 'Panadol, an NSAID', 'Pamol, an opioid', 'Paracetamol, an antibiotic'], src: ['deck-ma1', 'deck 01: clinical use classification'] },
    { id: 'p-ind', run: 'ma', drug: 'para', topic: 'Paracetamol', q: 'Why is Mr Luke on paracetamol?',
      a: 'For his recurrent backache.', keys: [['back']],
      opts: ['His recurrent backache', 'His high blood pressure', 'His heart failure', 'A fever this morning'], src: ['brief-ma', 'Scenario'] },
    { id: 'p-ae', run: 'ma', drug: 'para', topic: 'Paracetamol', q: 'What are the adverse effects of paracetamol?',
      a: 'Rare at the right dose: allergic reactions (rash, swelling).\nThe big risk: liver damage from too much.', keys: [['rash', 'allerg'], ['liver']],
      opts: ['Rare at the right dose: allergic rash; liver damage if too much', 'Very common: stomach bleeding and ulcers, even at normal everyday doses', 'Common: drowsiness and constipation, like the opioids', 'Common: a slow heart rate and dizziness when standing up'], src: ['ds-para', '4.8'] },
    { id: 'p-max', run: 'ma', drug: 'para', topic: 'Paracetamol', q: 'What’s the maximum dose, and the minimum gap between doses?',
      a: 'Max 4 g in 24 hours.\nAt least 4 hours apart.\n(He’s charted 4 g a day already, so no other paracetamol.)', keys: [['4 g', '4 grams', 'four grams', '4000'], ['4 hours', 'four hours']],
      opts: ['Max 4 g in 24 h, at least 4 hours apart', 'Max 8 g in 24 h, at least 2 hours apart', 'Max 2 g in 24 h, at least 8 hours apart', 'No max at 1 g doses, any time he asks'], src: ['ds-para', '4.2'] },
    { id: 'p-ask', run: 'ma', drug: 'para', topic: 'Paracetamol', q: 'What do you ask him before giving it?',
      a: 'When he last had paracetamol,\nincluding Panadol or cold-and-flu products from home.', keys: [['last', 'when'], ['panadol', 'cold', 'flu', 'other', 'home']],
      opts: ['When he last had any, including Panadol or cold-and-flu products', 'Whether he has eaten breakfast, because it must go with food', 'Whether he drives, because it causes drowsiness the same day', 'Whether he has asthma, because it is a beta blocker'], src: ['ds-para', '4.4'] },
    { id: 'p-dose', run: 'ma', drug: 'para', topic: 'Paracetamol', q: 'You have 500 mg tablets and the order is 1 g. How many?',
      a: 'Two tablets (1 g = 1000 mg; 1000 ÷ 500 = 2).', keys: [['two', '2']],
      opts: ['Two tablets', 'One tablet', 'Half a tablet', 'Four tablets'], src: ['brief-ma', 'Scenario'] },
    { id: 'o-name', run: 'ma', drug: 'meto', topic: 'Metoprolol', q: 'The pack says Betaloc CR. What’s the generic name, and what class is it?',
      a: 'Metoprolol succinate (controlled release).\nA beta-adrenoceptor blocker (beta blocker).', keys: [['metoprolol'], ['beta']],
      opts: ['Metoprolol succinate, a beta blocker', 'Betaloc, an ACE inhibitor', 'Metoprolol, a diuretic', 'Myloc, a calcium channel blocker'], src: ['deck-ma1', 'deck 01: clinical use classification'] },
    { id: 'o-ind', run: 'ma', drug: 'meto', topic: 'Metoprolol', q: 'Why is Mr Luke on metoprolol?',
      a: 'His high blood pressure (higher than usual lately)\nand his heart failure.', keys: [['pressure', 'hypertension'], ['heart']],
      opts: ['His high BP and his heart failure', 'His recurrent backache', 'An irregular fast heartbeat, nothing else', 'To help him sleep at night'], src: ['brief-ma', 'Scenario'] },
    { id: 'o-ae', run: 'ma', drug: 'meto', topic: 'Metoprolol', q: 'What are the common adverse effects of metoprolol?',
      a: 'Tiredness (very common).\nSlow heart rate, dizziness on standing, cold hands and feet.\nAlso headache, nausea, breathlessness on exertion.', keys: [['tired', 'fatigue'], ['slow', 'brady', 'dizz', 'cold']],
      opts: ['Tiredness, slow heart rate, dizziness on standing, cold hands and feet', 'Liver damage, allergic rash and a dry tickly cough from the first dose', 'A fast heart rate, high blood pressure and feeling hot all the time', 'Drowsiness, constipation and slowed breathing, like the opioids'], src: ['ds-meto', '4.8'] },
    { id: 'o-check', run: 'ma', drug: 'meto', topic: 'Metoprolol', q: 'What do you check before giving it?',
      a: 'His pulse and blood pressure.\nIf either is low, withhold and tell the RN.', keys: [['pulse', 'heart rate'], ['blood pressure', 'bp']],
      opts: ['His pulse and BP; if either is low, withhold and tell the RN', 'His temperature; if he has a fever, give it with paracetamol', 'His blood sugar; if it’s low, give it with something to eat', 'His oxygen saturation; if it’s low, give it with oxygen'], src: ['ds-meto', '4.4'] },
    { id: 'o-crush', run: 'ma', drug: 'meto', topic: 'Metoprolol', q: 'He struggles with tablets. Can you crush it?',
      a: 'No: it’s controlled release.\nIt can be halved, but never crushed or chewed.\nCheck with the RN or pharmacist.', keys: [['no', 'not', 'don’t', 'controlled', 'release'], ['halve', 'half', 'pharmacist']],
      opts: ['No: CR. It can be halved, never crushed; ask the pharmacist', 'Yes: crush it into yoghurt, which is fine for any tablet at all', 'Yes: let him chew it instead, which works just the same', 'No: give it as an injection instead, since that’s easier'], src: ['healthify', 'metoprolol'] },
    { id: 'o-stop', run: 'ma', drug: 'meto', topic: 'Metoprolol', q: 'What do you tell him about stopping it?',
      a: 'Don’t stop it suddenly.\nIt can make his heart failure worse.', keys: [['suddenly', 'stop'], ['heart', 'worse', 'dangerous', 'doctor']],
      opts: ['Never stop it suddenly; it can make his heart worse', 'Stop it whenever his blood pressure feels back to normal', 'Skip it on days when he feels dizzy or tired', 'Stop it after a week if he has no side effects'], src: ['ds-meto', '4.4'] },
    { id: 'o-falls', run: 'ma', drug: 'meto', topic: 'Metoprolol', q: 'What safety advice goes with it?',
      a: 'Stand up slowly.\nRing the bell before getting up for the next while: dizziness means a falls risk.', keys: [['slow', 'bell', 'ring'], ['dizz', 'fall']],
      opts: ['Stand up slowly and ring the bell before getting up: falls risk', 'Drink lots of coffee to counter the tiredness it causes him', 'Take it at night so any dizziness happens while he sleeps', 'Walk briskly after each dose to keep the blood pressure up'], src: ['healthify', 'metoprolol'] },
  ];

  window.CLS_RNQ = Q;
})();
